-- Project: HR Attrition Analysis
-- Dataset: IBM HR Analytics Employee Attrition
-- Source: https://www.kaggle.com/datasets/pavansubhasht/ibm-hr-analytics-attrition-dataset

CREATE TABLE hr_attrition (
  age INT,
  attrition VARCHAR(3),
  business_travel VARCHAR(30),
  daily_rate INT,
  department VARCHAR(50),
  distance_from_home INT,
  education INT,
  education_field VARCHAR(40),
  employee_count INT,
  employee_number INT PRIMARY KEY,
  environment_satisfaction INT,
  gender VARCHAR(10),
  hourly_rate INT,
  job_involvement INT,
  job_level INT,
  job_role VARCHAR(50),
  job_satisfaction INT,
  marital_status VARCHAR(15),
  monthly_income INT,
  monthly_rate INT,
  num_companies_worked INT,
  over_18 VARCHAR(1),
  over_time VARCHAR(3),
  percent_salary_hike INT,
  performance_rating INT,
  relationship_satisfaction INT,
  standard_hours INT,
  stock_option_level INT,
  total_working_years INT,
  training_times_last_year INT,
  work_life_balance INT,
  years_at_company INT,
  years_in_current_role INT,
  years_since_last_promotion INT,
  years_with_curr_manager INT
);